### ISSUE TITLE
Getting Hated - Thinking about quitting

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1479] opened 2016-09-24 01:11 UTC
Just look at #1478 - I'm getting soo much hate, and Its just tiring to have everyone getting mad at me whenever there is:
- lag
- Me restarting server
- Killing them or not teaming

I Want to have fun too guys! And i want to make you have fun too. Just please stop hating.
I will make my decision whether or not to stop running my server on October First.
Comment what you want me to do down below.

Bye The Way, I'm working on trying to make a new server that lags less.

**Comment by LegitSoulja** [comment] 2016-09-24 01:41
No, you don't have to make the client lag less since I am working on it. It's not the client for the cause of lag, but it does need a better efficient layout. But im already working on that.

I'll be closing down the client, forums, and statistics down today.

**Comment by ya345** [comment] 2016-09-24 01:42
I just saw it go down infront of my eyes... RIP

**Comment by SharkFinPro** [comment] 2016-09-24 02:00
@LegitSoulja Server, not client - oops
Im gonna recode it

**Comment by LegitSoulja** [comment] 2016-09-24 02:03
@SharkFinPro waste of time if it will be recreated better..
But, i mean, im not your guardian to tell you what to do, so by any means, do what you want I guess.

**Closed** 2016-09-24 07:55 UTC
