### ISSUE TITLE
i own a linux server . and i have some problems

### ISSUE THREAD

**Issue by xKG02** [AJS-development/Ogar-unlimited#1188] opened 2016-07-01 15:03 UTC
i own a linux server . and i have some problems :
 issue 1 : when i shut down the computer my ogar server shut down .
 issue 2 : and if i let my computer working , after 4 hours my ogar server shut down automatically .
 issue 3 : i dont know how to make my own page such as http://agarz.com/  
 issue 4 : i want to know more about the recommended settings for the server .
 issue 5 : i want to add many games in one server like : ffa , expermental , speedy , hunger games .

**Comment by Barbosik** [comment] 2016-07-01 15:47
issue 2: it's due to memory leaks

try MultiOgar: https://github.com/Barbosik/MultiOgar
It has no memory leaks, at least I hope :)
And it much faster. It can run up to 100-200 connected players with no lags, or up to 700-1000 bots with no lags.

**Comment by Agarian** [comment] 2016-07-01 15:50
and btw issue 2 can be partially fixed by garbage collection, its a config and a command

**Comment by Barbosik** [comment] 2016-07-01 15:53
Agarian: memory leaks cannot be fixed with garbage collection. Vice versa, garbage collection just add lags.

**Comment by Agarian** [comment] 2016-07-01 15:54
You're pretty much saying Andrews54757 added garbage collection for nothing.

**Comment by Barbosik** [comment] 2016-07-01 15:59
Using enforced garbage collection is just a struggle with the consequences, rather than the cause. You cannot eliminate memory leaks with such approach. It just add lags and allows to keep the server for a little more time, nothing else.

**Comment by systemroot** [comment] 2016-07-02 03:09
> issue 1 : when i shut down the computer my ogar server shut down . 

Use **screen** then **node index.js** And close terminal ,Putty or whatever, To get Ogar Console back login at linux server and write **screen -r**

How much ram do you have and CPU ?
to read RAM write in terminal **free -m**
and for CPU Is not needed more than 2 cpu to run ogar. And RAM is needed 3-4GB. And is good to make an Server reboot every day or one reboot every 2days. If you don't have too much ram than mount swap partition.

**Comment by Andrews54757** [comment] 2016-07-03 02:50
@Barbosik If I want to, I can eliminate lag once and for all. But, that would probably make certain people unhappy, like the fact that new bugs will come up. OgarUl is advancing in its own pace. I wish you good luck on your own project though. I think you've done a good job

**Comment by LegitSoulja** [comment] 2016-07-05 06:33
Issue (uno):
> If you are running a vps, maybe you should get this thing called **screen** that allows you to run processes without having to have either like **putty**, or any ssh application.

Issue (dos):
> Using garbage collector like agarian said could prevent your server from not leaking much data and ending up with a potential crash. Depending on your computer ram, and cpu if it can handle it for that long.

Issue (tres):
> We do not discuss on client hosting. It's pretty simple. These things you will need experience with.

Issue (cuatro):
> Everyone has difference preferences. Just make an offline test server that you can connect too and tinker around with the settings :)

Issue (cinco):
> You can add more than one game to a server by using the gamemode command. If you want a periodic gamemode changes you could make a plugin that does that which would be a cool thing to make. I would if you cant.

**P.S** : Closing this issue.

**Closed by LegitSoulja** 2016-07-05 06:33 UTC
