### ISSUE TITLE
I cant able to Join My server

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#306] opened 2016-03-27 19:03 UTC
after Few Hour of free time i am going to play on my server then i got to agar/?ip=localhost:28 but it dosent work

**Comment by PrinceDark9243** [comment] 2016-03-27 19:08
After That i got this error when i join
>TypeError: this.clients[i].playerTracker.antiTeamTick is not a function
    at GameServer.updateClients (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\src
\GameServer.js:1272:39)
    at GameServer.mainLoop (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\src\Game
Server.js:1107:14)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: Cannot set property 'x' of undefined
    at PacketHandler.handleMessage (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\
src\PacketHandler.js:81:32)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\node_modul
es\ws\lib\WebSocket.js:823:10)
    at D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\node_modules\ws\lib\Receiver.
js:537:18
    at Receiver.applyExtensions (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\nod
e_modules\ws\lib\Receiver.js:364:5)
    at D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\node_modules\ws\lib\Receiver.
js:531:14
    at Receiver.flush (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\node_modules\
ws\lib\Receiver.js:340:3)
    at Receiver.opcodes.2.finish (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\no
de_modules\ws\lib\Receiver.js:542:12)
    at Receiver.expectHandler (D:\Users\Papa\Desktop\Ogar-unlimited-11.6.3\node_
modules\ws\lib\Receiver.js:516:33)

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:32
Change the port to 8080 and stats to 8082

**Comment by firelightning13** [comment] 2016-03-27 19:34
@XtremePlayzCODE No this is other issue lol

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:40
Oh wow... is there a fix yet?

**Comment by firelightning13** [comment] 2016-03-27 19:40
Just wait for Andrew to fix it

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:40
Wait... I think that you should disable anti-team by allowing teams in the gameserver.ini

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:41
It says antiTeamTick and that has to be activated by antiteam in gameserver

**Comment by firelightning13** [comment] 2016-03-27 19:41
It's already disabled by default :/

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:41
Maybe he changed it dude

**Comment by ItzLevvie** [comment] 2016-03-27 19:42
@Andrews54757 He merged Cell.js into PlayerTracker.js

**Comment by firelightning13** [comment] 2016-03-27 19:42
No its not about enable or disable it, it missing a code

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:42
Why you want to merge cell and playertracker

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:42
Or even edit the whole thing

**Comment by firelightning13** [comment] 2016-03-27 19:42
He said ANDREW

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:43
Andrew didnt participate on this thread

**Comment by firelightning13** [comment] 2016-03-27 19:43
Andrew is the dev here ._.

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:43
But he was saying incase andrews looked at this

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:44
Lets stop arguing and try to help this guy

**Comment by firelightning13** [comment] 2016-03-27 19:45
Ok the problem is that when you download a fresh version, it starts normally, no errors. But when you join the game, you got error like the above.

sooooooooo.....

We just wait for @Andrews54757 to fix this

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:46
hmm... ill see what i can do aswell

**Comment by Andrews54757** [comment] 2016-03-27 19:48
its a mistake

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:49
@Andrews54757 Well... can't you fix it or what? lol, not trying to be rude or anything

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:50
Infact you're awesome

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:52
I can confirm this is infact an issue... Smae thing... perfectly fine but when you join the error pops up

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:57
OK, LOOKS LIKE ANDREW PATCHED THIS NOW

**Comment by Andrews54757** [comment] 2016-03-27 19:57
i fixed it, it was when I copied cell.js in my computer not playertraker

**Comment by XtremePlayzCODE** [comment] 2016-03-27 19:58
Noice andrew!

**Closed by Andrews54757** 2016-03-27 19:57 UTC
